#ifndef AVERYSTATUS_H
#define AVERYSTATUS_H
#include "stdint.h"
#include <stdbool.h>

/* status bit definitions */
#define STAT_ADC_FAULT                        0x000000001
#define STAT_TILT_SELF_TEST_ERROR             0x000000002
#define STAT_SERVICE_SWITCH                   0x000000004
#define STAT_VALIDATION_DATA_INVALID          0x000000008
#define STAT_WRITE_ENABLED                    0x000000010
#define STAT_TILT_OFFSETS_INVALID             0x000000020
#define STAT_TILT_CALIBRATION_INVALID         0x000000040
#define STAT_LOADCELL_CALIBRATION_INVALID     0x000000080
#define STAT_MANUFACTURE_DATA_INVALID         0x000000100
#define STAT_TILT_NOT_DETECTED                0x000000200
#define STAT_BOOTLOADER_RUNNING               0x000000400
#define STAT_CREEP_FACTORS_INVALID            0x000000800
#define STAT_CELL_VERIFIED                    0x000001000
#define STAT_TEMPERATURE_OFFSET_INVALID       0x000002000
#define STAT_CALIBRATION_TEMPERATURE_INVALID  0x000004000
#define STAT_TEMPERATURE_COEFFICIENTS_INVALID 0x000008000

#define NONVOL_WRITE_ACCESS (STAT_SERVICE_SWITCH | STAT_WRITE_ENABLED)

#define STAT_BOOT_INITIAL                                                                                               \
    (0 | STAT_ADC_FAULT | STAT_TILT_SELF_TEST_ERROR | STAT_SERVICE_SWITCH | STAT_VALIDATION_DATA_INVALID                \
     | STAT_WRITE_ENABLED | STAT_TILT_OFFSETS_INVALID | STAT_TILT_CALIBRATION_INVALID | STAT_TEMPERATURE_OFFSET_INVALID \
     | STAT_CALIBRATION_TEMPERATURE_INVALID | STAT_TEMPERATURE_COEFFICIENTS_INVALID | STAT_LOADCELL_CALIBRATION_INVALID \
     | STAT_MANUFACTURE_DATA_INVALID | STAT_TILT_NOT_DETECTED | STAT_BOOTLOADER_RUNNING | STAT_CREEP_FACTORS_INVALID)


      
      
uint32_t getWeigherStatus( void );
void setWeigherStatusBits( uint32_t bit );
void clrWeigherStatusBits( uint32_t bit );
bool isWeigherStatusBitSet( uint32_t bit );

#endif