/*
 * Copyright 2020 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/

/* Define the flexspi macro. Note that it can't be modified here */
#define IOMUXC_GPIO_AD_B1_00_FLEXSPI_A_DATA03 0x401F80FCU, 0x1U, 0x401F8374U, 0x1U, 0x401F8270U
#define IOMUXC_GPIO_AD_B1_01_FLEXSPI_A_SCLK 0x401F8100U, 0x1U, 0x401F8378U, 0x1U, 0x401F8274U
#define IOMUXC_GPIO_AD_B1_02_FLEXSPI_A_DATA00 0x401F8104U, 0x1U, 0x401F8368U, 0x1U, 0x401F8278U
#define IOMUXC_GPIO_AD_B1_03_FLEXSPI_A_DATA02 0x401F8108U, 0x1U, 0x401F8370U, 0x1U, 0x401F827CU
#define IOMUXC_GPIO_AD_B1_04_FLEXSPI_A_DATA01 0x401F810CU, 0x1U, 0x401F836CU, 0x1U, 0x401F8280U
#define IOMUXC_GPIO_AD_B1_05_FLEXSPI_A_SS0_B 0x401F8110U, 0x1U, 0, 0, 0x401F8284U

/*! @brief Direction type  */
typedef enum _pin_mux_direction
{
  kPIN_MUX_DirectionInput = 0U,         /* Input direction */
  kPIN_MUX_DirectionOutput = 1U,        /* Output direction */
  kPIN_MUX_DirectionInputOrOutput = 2U  /* Input or output direction */
} pin_mux_direction_t;

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

void BOARD_InitBootPins(void);
void BOARD_InitPins(void);
void configurePinAD_B1_15AsGPIO(void);
void configurePinAD_B1_15AsSPI3MISO(void);


//#define RK3568_ARK_REV_1_0_MOD  
/* Rev 1.0 mods: label taken led mod moved to emc_39 */ 
#define RK3568_ARK_REV_2_0_MOD
/******************************************************************************/    
/************************ rt1024-global scale *********************************/
/********************* sbc-rk3568-nxp24-ark rev 2.0 ***************************/        
/* Rev 2.0 changes from rev 1.0: 
      Pin:              From Signal:            To Signal:
    gpio_emc_09         LabelTakenEnable        LabelTakenLED
    gpio_emc_08         Spare                   ModelTypeIOB
    gpio_sd_b1_11       LabelTakenLED           LabelTakenEnable
    gpio_sd_b1_10       Spare                   StatusLedEnable
    gpio_sd_b1_09       Spare                   Logo2LedEnable
    gpio_sd_b1_08       Spare                   LogoLedEnable
    gpio_sd_b1_05       ModelTypeIOB            Spare
    gpio_ad_b0_08       Spare                   IDF1
    gpio_ad_b0_07       Spare                   IDF2
    gpio_ad_b1_06       Spare                   StatusLed2
    gpio_emc_22         Uart2Tx                 BootCFG
    gpio_emc_23         Uart2Rx                 BootCFG
*/ 
/******************************************************************************/
/********************************** weigher ***********************************/
/******************************************************************************/

#define WEIGHER_SPI_CLK_GPIO                            GPIO2
#define WEIGHER_SPI_CLK_PORT                            GPIO2
#define WEIGHER_SPI_CLK_PIN                             10U            

#define WEIGHER_SPI_MOSI_GPIO                           GPIO2
#define WEIGHER_SPI_MOSI_PORT                           GPIO2
#define WEIGHER_SPI_MOSI_PIN                            13U            

#define WEIGHER_SPI_MISO_GPIO                           GPIO2
#define WEIGHER_SPI_MISO_PORT                           GPIO2
#define WEIGHER_SPI_MISO_PIN                            12U            

#define WEIGHER_DATA_RDY_GPIO                           GPIO2
#define WEIGHER_DATA_RDY_PORT                           GPIO2
#define WEIGHER_DATA_RDY_PIN                            12U

#define WEIGHER_SPI_CS_GPIO                             GPIO2
#define WEIGHER_SPI_CS_PORT                             GPIO2
#define WEIGHER_SPI_CS_PIN                              11U            

#define WEIGHER_CLK_PWM_GPIO                            GPIO2
#define WEIGHER_CLK_PWM_PORT                            GPIO2
#define WEIGHER_CLK_PWM_PIN                             26U            

#define WGR_RESET_GPIO                                  GPIO3
#define WGR_RESET_PORT                                  GPIO3
#define WGR_RESET_PIN                                   5U

#define SERVICE_SWITCH_GPIO                             GPIO2
#define SERVICE_SWITCH_PORT                             GPIO2
#define SERVICE_SWITCH_PIN                              6U

#define ACCEL_I2C_SCL_PORT                              GPIO2    /* shared accel and lp5521 */   
#define ACCEL_I2C_SCL_GPIO                              GPIO2
#define ACCEL_I2C_SCL_PIN                               2U 

#define ACCEL_I2C_SDA_PORTx                             GPIO2
#define ACCEL_I2C_SDA_GPIOx                             GPIO2
#define ACCEL_I2C_SDA_PINx                              3U

#define ACCEL_SPI_CLK_GPIO                              GPIO1
#define ACCEL_SPI_CLK_PORT                              GPIO1
#define ACCEL_SPI_CLK_PIN                               28U

#define ACCEL_SPI_CS_GPIO                               GPIO1
#define ACCEL_SPI_CS_PORT                               GPIO1
#define ACCEL_SPI_CS_PIN                                29U

#define ACCEL_SPI_MOSI_GPIO                             GPIO1
#define ACCEL_SPI_MOSI_PORT                             GPIO1
#define ACCEL_SPI_MOSI_PIN                              30U

#define ACCEL_SPI_MISO_GPIO                             GPIO1
#define ACCEL_SPI_MISO_PORT                             GPIO1
#define ACCEL_SPI_MISO_PIN                              31U

#define ACCEL_INTA_PORT                                 GPIO2
#define ACCEL_INTA_GPIO                                 GPIO2
#define ACCEL_INTA_PIN                                  14U

#define ACCEL_INTB_PORT                                 GPIO2
#define ACCEL_INTB_GPIO                                 GPIO2
#define ACCEL_INTB_PIN                                  15U

#define ACCEL_PWR_EN_GPIO                               GPIO3
#define ACCEL_PWR_EN_PORT                               GPIO3
#define ACCEL_PWR_EN_PIN                                23U      //IOMUXC_GPIO_SD_B1_03_GPIO3_IO23

/******************************************************************************/
/******************************** communication *******************************/
/******************************************************************************/

#define RS485_TX_GPIO                                   GPIO1
#define RS485_TX_PORT                                   GPIO1
#define RS485_TX_PIN                                    10U

#define RS485_RX_GPIO                                   GPIO1
#define RS485_RX_PORT                                   GPIO1
#define RS485_RX_PIN                                    11U

#define CAN_TX_GPIO                                     GPIO3          
#define CAN_TX_PORT                                     GPIO3          
#define CAN_TX_PIN                                      20U
              
#define CAN_RX_GPIO                                     GPIO3                  
#define CAN_RX_PORT                                     GPIO3              
#define CAN_RX_PIN                                      21U 

#define USB_PWR_EN_GPIO                                 GPIO3
#define USB_PWR_EN_PORT                                 GPIO3
#define USB_PWR_EN_PIN                                  9U

#define USB_OTG1_ID_GPIO                                GPIO3
#define USB_OTG1_ID_PORT                                GPIO3
#define USB_OTG1_ID_PIN                                 8U

#define CUTTER_UART_TX_GPIO                             GPIO1
#define CUTTER_UART_TX_PORT                             GPIO1
#define CUTTER_UART_TX_PIN                              6U

#define CUTTER_UART_RX_GPIO                             GPIO1
#define CUTTER_UART_RX_PORT                             GPIO1
#define CUTTER_UART_RX_PIN                              7U

/******************************************************************************/
/********************************** printer ***********************************/   
/******************************************************************************/

#define PHEAD_SPI_CLK_GPIO                              GPIO3
#define PHEAD_SPI_CLK_PORT                              GPIO3
#define PHEAD_SPI_CLK_PIN                               0U

#define PHEAD_SPI_DATA_GPIO                             GPIO3
#define PHEAD_SPI_DATA_PORT                             GPIO3
#define PHEAD_SPI_DATA_PIN                              3U

#define PHEAD_LATCH_GPIO                                GPIO2
#define PHEAD_LATCH_PORT                                GPIO2
#define PHEAD_LATCH_PIN                                 0U

#define PHEAD_STROBE_A_GPIO                             GPIO3
#define PHEAD_STROBE_A_PORT                             GPIO3
#define PHEAD_STROBE_A_PIN                              6U

#define PHEAD_STROBE_B_GPIO                             GPIO3
#define PHEAD_STROBE_B_PORT                             GPIO3
#define PHEAD_STROBE_B_PIN                              22U

#define PHEAD_STROBE_EN_GPIO                            GPIO2
#define PHEAD_STROBE_EN_PORT                            GPIO2
#define PHEAD_STROBE_EN_PIN                             1U

#define PHEAD_POWER_EN_GPIO          	                GPIO2
#define PHEAD_POWER_EN_PORT          	                GPIO2
#define PHEAD_POWER_EN_PIN                              4U

#define PHEAD_DOT_ENABLE_GPIO          	                GPIO2    
#define PHEAD_DOT_ENABLE_PORT          	                GPIO2
#define PHEAD_DOT_ENABLE_PIN                            5U

#define PHEAD_DETECT_GPIO          	                GPIO1    
#define PHEAD_DETECT_GPIO_PORT          	        GPIO1
#define PHEAD_DETECT_GPIO_PIN                           15U


/******************************************************************************/
/********************************** motors ************************************/   
/******************************************************************************/

#define MAIN_MOTOR_SLEEP_GPIO                           GPIO3
#define MAIN_MOTOR_SLEEP_PORT                           GPIO3
#define MAIN_MOTOR_SLEEP_PIN                            4U

#define TAKEUP_MOTOR_MS0_GPIO                           GPIO2
#define TAKEUP_MOTOR_MS0_PORT                           GPIO2
#define TAKEUP_MOTOR_MS0_PIN                            16U

#define TAKEUP_MOTOR_MS1_GPIO                           GPIO2
#define TAKEUP_MOTOR_MS1_PORT                           GPIO2
#define TAKEUP_MOTOR_MS1_PIN                            17U

#define TAKEUP_MOTOR_RESET_GPIO                         GPIO2
#define TAKEUP_MOTOR_RESET_PORT                         GPIO2
#define TAKEUP_MOTOR_RESET_PIN                          18U

#define TAKEUP_MOTOR_EN_GPIO                            GPIO2
#define TAKEUP_MOTOR_EN_PORT                            GPIO2
#define TAKEUP_MOTOR_EN_PIN                             19U

#define TAKEUP_MOTOR_DIR_GPIO                           GPIO2
#define TAKEUP_MOTOR_DIR_PORT                           GPIO2
#define TAKEUP_MOTOR_DIR_PIN                            20U

#define TAKEUP_MOTOR_STEP_GPIO                          GPIO2
#define TAKEUP_MOTOR_STEP_PORT                          GPIO2
#define TAKEUP_MOTOR_STEP_PIN                           21U

#define TAKEUP_MOTOR_SLEEP_GPIO                         GPIO2
#define TAKEUP_MOTOR_SLEEP_PORT                         GPIO2
#define TAKEUP_MOTOR_SLEEP_PIN                          24U

#define MAIN_MOTOR_MS0_GPIO                             GPIO2
#define MAIN_MOTOR_MS0_PORT                             GPIO2
#define MAIN_MOTOR_MS0_PIN                              25U

#define MAIN_MOTOR_MS1_GPIO                             GPIO2
#define MAIN_MOTOR_MS1_PORT                             GPIO2
#define MAIN_MOTOR_MS1_PIN                              27U

#define MAIN_MOTOR_RESET_GPIO                           GPIO2
#define MAIN_MOTOR_RESET_PORT                           GPIO2
#define MAIN_MOTOR_RESET_PIN                            28U

#define MOTOR_EN_GPIO                                   GPIO2
#define MOTOR_EN_PORT                                   GPIO2
#define MOTOR_EN_PIN                                    29U 

#define MAIN_MOTOR_DIR_GPIO                             GPIO2            
#define MAIN_MOTOR_DIR_PORT                             GPIO2
#define MAIN_MOTOR_DIR_PIN                              30U

#define MAIN_MOTOR_STEP_GPIO                            GPIO2
#define MAIN_MOTOR_STEP_PORT                            GPIO2
#define MAIN_MOTOR_STEP_PIN                             31U

/******************************************************************************/
/********************************** misc io ***********************************/   
/******************************************************************************/

#define SERIAL_FlASH_CS_GPIO                            GPIO3
#define SERIAL_FlASH_CS_PORT                            GPIO3
#define SERIAL_FlASH_CS_PIN                             16U    


#define LP5521_EN_GPIO                                  GPIO2
#define LP5521_EN_PORT                                  GPIO2
#define LP5521_EN_PIN                                   7U


#ifdef RK3568_ARK_REV_1_0_MOD 

#define LABEL_TAKEN_LED_GPIO                            GPIO2
#define LABEL_TAKEN_LED_PORT                            GPIO2
#define LABEL_TAKEN_LED_PIN                             21U

#else 

#ifdef RK3568_ARK_REV_2_0_MOD

#define LABEL_TAKEN_LED_GPIO                            GPIO2
#define LABEL_TAKEN_LED_PORT                            GPIO2
#define LABEL_TAKEN_LED_PIN                             9U

#else 

#endif

#endif

#define LABEL_TAKEN_EN_PORT                             GPIO3                         
#define LABEL_TAKEN_EN_GPIO                             GPIO3
#define LABEL_TAKEN_EN_PIN                              31U

#define SRAM_CS_GPIO                                    GPIO3
#define SRAM_CS_PORT                                    GPIO3
#define SRAM_CS_PIN                                     1U

#define SRAM_MISO_GPIO                                  GPIO3
#define SRAM_MISO_PORT                                  GPIO3
#define SRAM_MISO_PIN                                   2U

#define MODEL_TYPE_A_GPIO                               GPIO3                             
#define MODEL_TYPE_A_PORT                               GPIO3
#define MODEL_TYPE_A_PIN                                24U

#define MODEL_TYPE_B_GPIO                               GPIO2                               
#define MODEL_TYPE_B_PORT                               GPIO2
#define MODEL_TYPE_B_PIN                                8U

#define MODEL_TYPE_C_GPIO                               GPIO3                               
#define MODEL_TYPE_C_PORT                               GPIO3
#define MODEL_TYPE_C_PIN                                26U

#define MODEL_TYPE_D_GPIO                               GPIO3                               
#define MODEL_TYPE_D_PORT                               GPIO3
#define MODEL_TYPE_D_PIN                                27U

#define IDF1_GPIO                                       GPIO1                               
#define IDF1_PORT                                       GPIO1
#define IDF1_PIN                                        8U

#define IDF2_GPIO                                       GPIO1                               
#define IDF2_PORT                                       GPIO1
#define IDF2_PIN                                        9U

#define HEART_BEAT_LED_GPIO                             GPIO3          
#define HEART_BEAT_LED_PORT                             GPIO3           
#define HEART_BEAT_LED_PIN                              14U  

#define LOGO_EN1_LED_GPIO                               GPIO3          
#define LOGO_EN1_LED_PORT                               GPIO3           
#define LOGO_EN1_LED_PIN                                29U  

#define LOGO_EN_LED_GPIO                                GPIO3          
#define LOGO_EN_LED_PORT                                GPIO3           
#define LOGO_EN_LED_PIN                                 28U  

#define LOGO_STATUS_LED_EN_GPIO                         GPIO3          
#define LOGO_STATUS_LED_EN_PORT                         GPIO3           
#define LOGO_STATUS_LED_EN_PIN                          30U  

#define STATUS_LED_GPIO                                 GPIO1
#define STATUS_LED_PORT                                 GPIO1           
#define STATUS_LED_PIN                                  22U  

/******************************************************************************/
/********************************** sensors ***********************************/   
/******************************************************************************/

#define LABEL_TAKEN_SENSOR_GPIO                         GPIO1                                         
#define LABEL_TAKEN_SENSOR_PORT                         GPIO1                
#define LABEL_TAKEN_SENSOR_PIN                          13U               

#define LOW_LABEL_STOCK_SENSOR_GPIO                     GPIO1
#define LOW_LABEL_STOCK_SENSOR_PORT                     GPIO1
#define LOW_LABEL_STOCK_SENSOR_PIN                      14U

#define SHOOT_THROUGH_SENSOR_GPIO                       GPIO1
#define SHOOT_THROUGH_SENSOR_PORT                       GPIO1
#define SHOOT_THROUGH_SENSOR_PIN                        23U

#define PAPER_TAKEUP_SENSOR_GPIO                        GPIO1
#define PAPER_TAKEUP_SENSOR_PORT                        GPIO1
#define PAPER_TAKEUP_SENSOR_PIN                         24U

#define PHEAD_THERM_SENSOR_GPIO                         GPIO1
#define PHEAD_THERM_SENSOR_PORT                         GPIO1
#define PHEAD_THERM_SENSOR_PIN                          25U

#define HEAD_UP_SENSOR_GPIO                             GPIO1         	  
#define HEAD_UP_SENSOR_PORT                             GPIO1     	  
#define HEAD_UP_SENSOR_PIN                              26U

#define PHEAD_DOT_GPIO                                  GPIO1         	  
#define PHEAD_DOT_PORT                                  GPIO1     	  
#define PHEAD_DOT_PIN                                   27U

/******************************************************************************/    
/******************************************************************************/    
/******************************************************************************/    
#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
