/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/

/* Define the flexspi macro. Note that it can't be modified here */
#define IOMUXC_GPIO_AD_B1_00_FLEXSPI_A_DATA03 0x401F80FCU, 0x1U, 0x401F8374U, 0x1U, 0x401F8270U
#define IOMUXC_GPIO_AD_B1_01_FLEXSPI_A_SCLK 0x401F8100U, 0x1U, 0x401F8378U, 0x1U, 0x401F8274U
#define IOMUXC_GPIO_AD_B1_02_FLEXSPI_A_DATA00 0x401F8104U, 0x1U, 0x401F8368U, 0x1U, 0x401F8278U
#define IOMUXC_GPIO_AD_B1_03_FLEXSPI_A_DATA02 0x401F8108U, 0x1U, 0x401F8370U, 0x1U, 0x401F827CU
#define IOMUXC_GPIO_AD_B1_04_FLEXSPI_A_DATA01 0x401F810CU, 0x1U, 0x401F836CU, 0x1U, 0x401F8280U
#define IOMUXC_GPIO_AD_B1_05_FLEXSPI_A_SS0_B 0x401F8110U, 0x1U, 0, 0, 0x401F8284U

/*! @brief Direction type  */
typedef enum _pin_mux_direction
{
  kPIN_MUX_DirectionInput = 0U,         /* Input direction */
  kPIN_MUX_DirectionOutput = 1U,        /* Output direction */
  kPIN_MUX_DirectionInputOrOutput = 2U  /* Input or output direction */
} pin_mux_direction_t;

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/* GPIO_AD_B0_12 (number 96), Shoot Through */
#define BOARD_INITPINS_SHOOT_THROUGH_PERIPHERAL                             ADC1   /*!< Device name: ADC1 */
#define BOARD_INITPINS_SHOOT_THROUGH_SIGNAL                                   IN   /*!< ADC1 signal: IN */
#define BOARD_INITPINS_SHOOT_THROUGH_CHANNEL                                  0U   /*!< ADC1 IN channel: 0 */

/* GPIO_AD_B0_14 (number 94), Print Head Voltage */
#define BOARD_INITPINS_PRINT_HEAD_VOLTAGE_PERIPHERAL                        ADC1   /*!< Device name: ADC1 */
#define BOARD_INITPINS_PRINT_HEAD_VOLTAGE_SIGNAL                              IN   /*!< ADC1 signal: IN */
#define BOARD_INITPINS_PRINT_HEAD_VOLTAGE_CHANNEL                             1U   /*!< ADC1 IN channel: 1 */

/* GPIO_AD_B0_15 (number 93), Print Head Thermal */
#define BOARD_INITPINS_PRINT_HEAD_THERMAL_PERIPHERAL                        ADC1   /*!< Device name: ADC1 */
#define BOARD_INITPINS_PRINT_HEAD_THERMAL_SIGNAL                              IN   /*!< ADC1 signal: IN */
#define BOARD_INITPINS_PRINT_HEAD_THERMAL_CHANNEL                             2U   /*!< ADC1 IN channel: 2 */

/* GPIO_AD_B1_06 (number 84), Media Sensor */
#define BOARD_INITPINS_MEDIA_SENSOR_PERIPHERAL                              ADC1   /*!< Device name: ADC1 */
#define BOARD_INITPINS_MEDIA_SENSOR_SIGNAL                                    IN   /*!< ADC1 signal: IN */
#define BOARD_INITPINS_MEDIA_SENSOR_CHANNEL                                   6U   /*!< ADC1 IN channel: 6 */

/* GPIO_AD_B1_07 (number 83), Model Type */
#define BOARD_INITPINS_MODEL_TYPE_PERIPHERAL                                ADC1   /*!< Device name: ADC1 */
#define BOARD_INITPINS_MODEL_TYPE_SIGNAL                                      IN   /*!< ADC1 signal: IN */
#define BOARD_INITPINS_MODEL_TYPE_CHANNEL                                     7U   /*!< ADC1 IN channel: 7 */

/* GPIO_AD_B1_08 (number 82), Dot Wear */
#define BOARD_INITPINS_DOT_WEAR_PERIPHERAL                                  ADC1   /*!< Device name: ADC1 */
#define BOARD_INITPINS_DOT_WEAR_SIGNAL                                        IN   /*!< ADC1 signal: IN */
#define BOARD_INITPINS_DOT_WEAR_CHANNEL                                       8U   /*!< ADC1 IN channel: 8 */

/* GPIO_AD_B1_09 (number 81), Head Up */
#define BOARD_INITPINS_HEADUP_PERIPHERAL                                    ADC1   /*!< Device name: ADC1 */
#define BOARD_INITPINS_HEADUP_SIGNAL                                          IN   /*!< ADC1 signal: IN */
#define BOARD_INITPINS_HEADUP_CHANNEL                                         9U   /*!< ADC1 IN channel: 9 */

/* GPIO_AD_B0_02 (number 109), Jtag Mod */
#define BOARD_INITPINS_JTAG_MOD_PERIPHERAL                                  JTAG   /*!< Device name: JTAG */
#define BOARD_INITPINS_JTAG_MOD_SIGNAL                                       MOD   /*!< JTAG signal: MOD */

/* GPIO_AD_B0_01 (number 110), Jtag Tck */
#define BOARD_INITPINS_JTAG_TCK_PERIPHERAL                                  JTAG   /*!< Device name: JTAG */
#define BOARD_INITPINS_JTAG_TCK_SIGNAL                                       TCK   /*!< JTAG signal: TCK */

/* GPIO_AD_B0_03 (number 108), Jtag Tdi */
#define BOARD_INITPINS_JTAG_TDI_PERIPHERAL                                  JTAG   /*!< Device name: JTAG */
#define BOARD_INITPINS_JTAG_TDI_SIGNAL                                       TDI   /*!< JTAG signal: TDI */

/* GPIO_AD_B0_04 (number 107), Jtag Tdo */
#define BOARD_INITPINS_JTAG_TDO_PERIPHERAL                                  JTAG   /*!< Device name: JTAG */
#define BOARD_INITPINS_JTAG_TDO_SIGNAL                                       TDO   /*!< JTAG signal: TDO */

/* GPIO_AD_B0_00 (number 111), Jtag Tms */
#define BOARD_INITPINS_JTAG_TMS_PERIPHERAL                                  JTAG   /*!< Device name: JTAG */
#define BOARD_INITPINS_JTAG_TMS_SIGNAL                                       TMS   /*!< JTAG signal: TMS */

/* GPIO_AD_B0_05 (number 106), Jtag Trstb */
#define BOARD_INITPINS_JTAG_TRSTB_PERIPHERAL                                JTAG   /*!< Device name: JTAG */
#define BOARD_INITPINS_JTAG_TRSTB_SIGNAL                                   TRSTB   /*!< JTAG signal: TRSTB */

/* GPIO_EMC_14 (number 1), Weigher Clk */
#define BOARD_INITPINS_WEIGHER_CLK_PERIPHERAL                               PWM1   /*!< Device name: PWM1 */
#define BOARD_INITPINS_WEIGHER_CLK_SIGNAL                                    EXT   /*!< PWM1 signal: EXT */
#define BOARD_INITPINS_WEIGHER_CLK_CHANNEL                                    A0   /*!< PWM1 EXT channel: A0 */

/* GPIO_SD_B0_03 (number 45), Serial Spi CS */
#define BOARD_INITPINS_SERIAL_SPI_CS_PERIPHERAL                           LPSPI1   /*!< Device name: LPSPI1 */
#define BOARD_INITPINS_SERIAL_SPI_CS_SIGNAL                                 PCS0   /*!< LPSPI1 signal: PCS0 */

/* GPIO_SD_B0_02 (number 46), Serial Spi CLK */
#define BOARD_INITPINS_SERIAL_SPI_CLK_PERIPHERAL                          LPSPI1   /*!< Device name: LPSPI1 */
#define BOARD_INITPINS_SERIAL_SPI_CLK_SIGNAL                                 SCK   /*!< LPSPI1 signal: SCK */

/* GPIO_SD_B0_05 (number 42), Serial Spi MISO */
#define BOARD_INITPINS_SERIAL_SPI_MISO_PERIPHERAL                         LPSPI1   /*!< Device name: LPSPI1 */
#define BOARD_INITPINS_SERIAL_SPI_MISO_SIGNAL                                SDI   /*!< LPSPI1 signal: SDI */

/* GPIO_SD_B0_04 (number 43), Serial Spi MOSI */
#define BOARD_INITPINS_SERIAL_SPI_MOSI_PERIPHERAL                         LPSPI1   /*!< Device name: LPSPI1 */
#define BOARD_INITPINS_SERIAL_SPI_MOSI_SIGNAL                                SDO   /*!< LPSPI1 signal: SDO */

/* GPIO_EMC_11 (number 4), Weigher Spi CS */
#define BOARD_INITPINS_WEIGHER_SPI_CS_PERIPHERAL                          LPSPI2   /*!< Device name: LPSPI2 */
#define BOARD_INITPINS_WEIGHER_SPI_CS_SIGNAL                                PCS0   /*!< LPSPI2 signal: PCS0 */

/* GPIO_EMC_10 (number 7), Weigher Spi CLK */
#define BOARD_INITPINS_WEIGHER_SPI_CLK_PERIPHERAL                         LPSPI2   /*!< Device name: LPSPI2 */
#define BOARD_INITPINS_WEIGHER_SPI_CLK_SIGNAL                                SCK   /*!< LPSPI2 signal: SCK */

/* GPIO_EMC_13 (number 2), Weigher Spi MISO */
#define BOARD_INITPINS_WEIGHER_SPI_MISO_PERIPHERAL                        LPSPI2   /*!< Device name: LPSPI2 */
#define BOARD_INITPINS_WEIGHER_SPI_MISO_SIGNAL                               SDI   /*!< LPSPI2 signal: SDI */

/* GPIO_EMC_12 (number 3), Weigher Spi MOSI */
#define BOARD_INITPINS_WEIGHER_SPI_MOSI_PERIPHERAL                        LPSPI2   /*!< Device name: LPSPI2 */
#define BOARD_INITPINS_WEIGHER_SPI_MOSI_SIGNAL                               SDO   /*!< LPSPI2 signal: SDO */

/* GPIO_AD_B1_14 (number 75), Accel Spi MOSI */
#define BOARD_INITPINS_ACCEL_SPI_MOSI_PERIPHERAL                          LPSPI3   /*!< Device name: LPSPI3 */
#define BOARD_INITPINS_ACCEL_SPI_MOSI_SIGNAL                                 SDO   /*!< LPSPI3 signal: SDO */

/* GPIO_AD_B1_15 (number 74), Accel Spi MISO */
#define BOARD_INITPINS_ACCEL_SPI_MISO_PERIPHERAL                          LPSPI3   /*!< Device name: LPSPI3 */
#define BOARD_INITPINS_ACCEL_SPI_MISO_SIGNAL                                 SDI   /*!< LPSPI3 signal: SDI */

/* GPIO_EMC_34 (number 122), Print Head Data */
#define BOARD_INITPINS_PRINT_HEAD_DATA_PERIPHERAL                         LPSPI4   /*!< Device name: LPSPI4 */
#define BOARD_INITPINS_PRINT_HEAD_DATA_SIGNAL                                SDO   /*!< LPSPI4 signal: SDO */

/* GPIO_EMC_35 (number 121), Unused */
#define BOARD_INITPINS_UNUSED_PERIPHERAL                                  LPSPI4   /*!< Device name: LPSPI4 */
#define BOARD_INITPINS_UNUSED_SIGNAL                                         SDI   /*!< LPSPI4 signal: SDI */

/* GPIO_EMC_32 (number 124), Print Head CLK */
#define BOARD_INITPINS_PRINT_HEAD_CLK_PERIPHERAL                          LPSPI4   /*!< Device name: LPSPI4 */
#define BOARD_INITPINS_PRINT_HEAD_CLK_SIGNAL                                 SCK   /*!< LPSPI4 signal: SCK */

/* GPIO_EMC_39 (number 117), Usb OC */
#define BOARD_INITPINS_USB_OC_PERIPHERAL                                     USB   /*!< Device name: USB */
#define BOARD_INITPINS_USB_OC_SIGNAL                                 usb_otg1_oc   /*!< USB signal: usb_otg1_oc */

/* GPIO_EMC_41 (number 115), Usb Pwr */
#define BOARD_INITPINS_USB_PWR_PERIPHERAL                                    USB   /*!< Device name: USB */
#define BOARD_INITPINS_USB_PWR_SIGNAL                               usb_otg1_pwr   /*!< USB signal: usb_otg1_pwr */

/* GPIO_EMC_40 (number 116), Usb Id */
#define BOARD_INITPINS_USB_ID_PERIPHERAL                                     USB   /*!< Device name: USB */
#define BOARD_INITPINS_USB_ID_SIGNAL                                 usb_otg1_id   /*!< USB signal: usb_otg1_id */

/* GPIO_AD_B1_12 (number 78), Accel Spi Clk */
#define BOARD_INITPINS_ACCEL_SPI_CLK_PERIPHERAL                           LPSPI3   /*!< Device name: LPSPI3 */
#define BOARD_INITPINS_ACCEL_SPI_CLK_SIGNAL                                  SCK   /*!< LPSPI3 signal: SCK */

/* GPIO_AD_B1_13 (number 76), Accel Spi CS */
#define BOARD_INITPINS_ACCEL_SPI_CS_PERIPHERAL                            LPSPI3   /*!< Device name: LPSPI3 */
#define BOARD_INITPINS_ACCEL_SPI_CS_SIGNAL                                  PCS0   /*!< LPSPI3 signal: PCS0 */

/* GPIO_AD_B0_07 (number 101), Cutter Uart Rx */
#define BOARD_INITPINS_CUTTER_UART_RX_PERIPHERAL                         LPUART1   /*!< Device name: LPUART1 */
#define BOARD_INITPINS_CUTTER_UART_RX_SIGNAL                                  RX   /*!< LPUART1 signal: RX */

/* GPIO_AD_B0_06 (number 105), Cutter Uart Tx */
#define BOARD_INITPINS_CUTTER_UART_TX_PERIPHERAL                         LPUART1   /*!< Device name: LPUART1 */
#define BOARD_INITPINS_CUTTER_UART_TX_SIGNAL                                  TX   /*!< LPUART1 signal: TX */

/* GPIO_EMC_23 (number 133), Debug Uart Rx */
#define BOARD_INITPINS_DEBUG_UART_RX_PERIPHERAL                          LPUART2   /*!< Device name: LPUART2 */
#define BOARD_INITPINS_DEBUG_UART_RX_SIGNAL                                   RX   /*!< LPUART2 signal: RX */

/* GPIO_EMC_22 (number 136), Debug Uart Tx */
#define BOARD_INITPINS_DEBUG_UART_TX_PERIPHERAL                          LPUART2   /*!< Device name: LPUART2 */
#define BOARD_INITPINS_DEBUG_UART_TX_SIGNAL                                   TX   /*!< LPUART2 signal: TX */

/* GPIO_EMC_02 (number 16), Pwm 5/25 Clk */
#define BOARD_INITPINS_PWM_5_25_CLK_PERIPHERAL                            LPI2C1   /*!< Device name: LPI2C1 */
#define BOARD_INITPINS_PWM_5_25_CLK_SIGNAL                                   SCL   /*!< LPI2C1 signal: SCL */

/* GPIO_EMC_03 (number 15), Pwm 5/25 Data */
#define BOARD_INITPINS_PWM_5_25_DATA_PERIPHERAL                           LPI2C1   /*!< Device name: LPI2C1 */
#define BOARD_INITPINS_PWM_5_25_DATA_SIGNAL                                  SDA   /*!< LPI2C1 signal: SDA */

/* GPIO_EMC_00 (number 18), Label Taken */
#define BOARD_INITPINS_LABEL_TAKEN_GPIO                                    GPIO2   /*!< GPIO device name: GPIO2 */
#define BOARD_INITPINS_LABEL_TAKEN_PORT                                    GPIO2   /*!< PORT device name: GPIO2 */
#define BOARD_INITPINS_LABEL_TAKEN_PIN                                        0U   /*!< GPIO2 pin index: 0 */

/* GPIO_EMC_01 (number 17), Print Head Detect */
#define BOARD_INITPINS_PRINT_HEAD_DETECT_GPIO                              GPIO2   /*!< GPIO device name: GPIO2 */
#define BOARD_INITPINS_PRINT_HEAD_DETECT_PORT                              GPIO2   /*!< PORT device name: GPIO2 */
#define BOARD_INITPINS_PRINT_HEAD_DETECT_PIN                                  1U   /*!< GPIO2 pin index: 1 */

/* GPIO_EMC_04 (number 14), Print Head Id0 */
#define BOARD_INITPINS_PRINT_HEAD_ID0_GPIO                                 GPIO2   /*!< GPIO device name: GPIO2 */
#define BOARD_INITPINS_PRINT_HEAD_ID0_PORT                                 GPIO2   /*!< PORT device name: GPIO2 */
#define BOARD_INITPINS_PRINT_HEAD_ID0_PIN                                     4U   /*!< GPIO2 pin index: 4 */

/* GPIO_EMC_05 (number 13), Print Head Id1 */
#define BOARD_INITPINS_PRINT_HEAD_ID1_GPIO                                 GPIO2   /*!< GPIO device name: GPIO2 */
#define BOARD_INITPINS_PRINT_HEAD_ID1_PORT                                 GPIO2   /*!< PORT device name: GPIO2 */
#define BOARD_INITPINS_PRINT_HEAD_ID1_PIN                                     5U   /*!< GPIO2 pin index: 5 */

/* GPIO_EMC_06 (number 12), Print Head Id2 */
#define BOARD_INITPINS_PRINT_HEAD_ID2_GPIO                                 GPIO2   /*!< GPIO device name: GPIO2 */
#define BOARD_INITPINS_PRINT_HEAD_ID2_PORT                                 GPIO2   /*!< PORT device name: GPIO2 */
#define BOARD_INITPINS_PRINT_HEAD_ID2_PIN                                     6U   /*!< GPIO2 pin index: 6 */

/* GPIO_EMC_07 (number 10), Print Head Strobe EN */
#define BOARD_INITPINS_PRINT_HEAD_STROBE_EN_GPIO                           GPIO2   /*!< GPIO device name: GPIO2 */
#define BOARD_INITPINS_PRINT_HEAD_STROBE_EN_PORT                           GPIO2   /*!< PORT device name: GPIO2 */
#define BOARD_INITPINS_PRINT_HEAD_STROBE_EN_PIN                               7U   /*!< GPIO2 pin index: 7 */

/* GPIO_EMC_08 (number 9), Print Head Latch */
#define BOARD_INITPINS_PRINT_HEAD_LATCH_GPIO                               GPIO2   /*!< GPIO device name: GPIO2 */
#define BOARD_INITPINS_PRINT_HEAD_LATCH_PORT                               GPIO2   /*!< PORT device name: GPIO2 */
#define BOARD_INITPINS_PRINT_HEAD_LATCH_PIN                                   8U   /*!< GPIO2 pin index: 8 */

/* GPIO_EMC_09 (number 8), Print Head Strobe */
#define BOARD_INITPINS_PRINT_HEAD_STROBE_GPIO                              GPIO2   /*!< GPIO device name: GPIO2 */
#define BOARD_INITPINS_PRINT_HEAD_STROBE_PORT                              GPIO2   /*!< PORT device name: GPIO2 */
#define BOARD_INITPINS_PRINT_HEAD_STROBE_PIN                                  9U   /*!< GPIO2 pin index: 9 */

/* GPIO_EMC_15 (number 143), Print Head Pwr EN */
#define BOARD_INITPINS_PRINT_HEAD_PWR_EN_GPIO                              GPIO2   /*!< GPIO device name: GPIO2 */
#define BOARD_INITPINS_PRINT_HEAD_PWR_EN_PORT                              GPIO2   /*!< PORT device name: GPIO2 */
#define BOARD_INITPINS_PRINT_HEAD_PWR_EN_PIN                                 15U   /*!< GPIO2 pin index: 15 */

/* GPIO_SD_B1_00 (number 33), Main Stepper Step */
#define BOARD_INITPINS_MAIN_STEPPER_STEP_GPIO                              GPIO3   /*!< GPIO device name: GPIO3 */
#define BOARD_INITPINS_MAIN_STEPPER_STEP_PORT                              GPIO3   /*!< PORT device name: GPIO3 */
#define BOARD_INITPINS_MAIN_STEPPER_STEP_PIN                                 20U   /*!< GPIO3 pin index: 20 */

/* GPIO_SD_B1_01 (number 32), Main Stepper Dir */
#define BOARD_INITPINS_MAIN_STEPPER_DIR_GPIO                               GPIO3   /*!< GPIO device name: GPIO3 */
#define BOARD_INITPINS_MAIN_STEPPER_DIR_PORT                               GPIO3   /*!< PORT device name: GPIO3 */
#define BOARD_INITPINS_MAIN_STEPPER_DIR_PIN                                  21U   /*!< GPIO3 pin index: 21 */

/* GPIO_SD_B1_02 (number 30), Main Stepper EN */
#define BOARD_INITPINS_MAIN_STEPPER_EN_GPIO                                GPIO3   /*!< GPIO device name: GPIO3 */
#define BOARD_INITPINS_MAIN_STEPPER_EN_PORT                                GPIO3   /*!< PORT device name: GPIO3 */
#define BOARD_INITPINS_MAIN_STEPPER_EN_PIN                                   22U   /*!< GPIO3 pin index: 22 */

/* GPIO_SD_B1_03 (number 28), Main Stepper Rst */
#define BOARD_INITPINS_MAIN_STEPPER_RST_GPIO                               GPIO3   /*!< GPIO device name: GPIO3 */
#define BOARD_INITPINS_MAIN_STEPPER_RST_PORT                               GPIO3   /*!< PORT device name: GPIO3 */
#define BOARD_INITPINS_MAIN_STEPPER_RST_PIN                                  23U   /*!< GPIO3 pin index: 23 */

/* GPIO_SD_B1_04 (number 27), Main Stepper MS1 */
#define BOARD_INITPINS_MAIN_STEPPER_MS1_GPIO                               GPIO3   /*!< GPIO device name: GPIO3 */
#define BOARD_INITPINS_MAIN_STEPPER_MS1_PORT                               GPIO3   /*!< PORT device name: GPIO3 */
#define BOARD_INITPINS_MAIN_STEPPER_MS1_PIN                                  24U   /*!< GPIO3 pin index: 24 */

/* GPIO_SD_B1_05 (number 26), Main Stepper MS2 */
#define BOARD_INITPINS_MAIN_STEPPER_MS2_GPIO                               GPIO3   /*!< GPIO device name: GPIO3 */
#define BOARD_INITPINS_MAIN_STEPPER_MS2_PORT                               GPIO3   /*!< PORT device name: GPIO3 */
#define BOARD_INITPINS_MAIN_STEPPER_MS2_PIN                                  25U   /*!< GPIO3 pin index: 25 */

/* GPIO_SD_B1_06 (number 25), TakeUp Stepper Step */
#define BOARD_INITPINS_TAKEUP_STEPPER_STEP_GPIO                            GPIO3   /*!< GPIO device name: GPIO3 */
#define BOARD_INITPINS_TAKEUP_STEPPER_STEP_PORT                            GPIO3   /*!< PORT device name: GPIO3 */
#define BOARD_INITPINS_TAKEUP_STEPPER_STEP_PIN                               26U   /*!< GPIO3 pin index: 26 */

/* GPIO_SD_B1_07 (number 24), TakeUp Stepper Dir */
#define BOARD_INITPINS_TAKEUP_STEPPER_DIR_GPIO                             GPIO3   /*!< GPIO device name: GPIO3 */
#define BOARD_INITPINS_TAKEUP_STEPPER_DIR_PORT                             GPIO3   /*!< PORT device name: GPIO3 */
#define BOARD_INITPINS_TAKEUP_STEPPER_DIR_PIN                                27U   /*!< GPIO3 pin index: 27 */

/* GPIO_SD_B1_08 (number 23), TakeUp Stepper EN */
#define BOARD_INITPINS_TAKEUP_STEPPER_EN_GPIO                              GPIO3   /*!< GPIO device name: GPIO3 */
#define BOARD_INITPINS_TAKEUP_STEPPER_EN_PORT                              GPIO3   /*!< PORT device name: GPIO3 */
#define BOARD_INITPINS_TAKEUP_STEPPER_EN_PIN                                 28U   /*!< GPIO3 pin index: 28 */

/* GPIO_SD_B1_09 (number 22), TakeUp Stepper Rst */
#define BOARD_INITPINS_TAKEUP_STEPPER_RST_GPIO                             GPIO3   /*!< GPIO device name: GPIO3 */
#define BOARD_INITPINS_TAKEUP_STEPPER_RST_PORT                             GPIO3   /*!< PORT device name: GPIO3 */
#define BOARD_INITPINS_TAKEUP_STEPPER_RST_PIN                                29U   /*!< GPIO3 pin index: 29 */

/* GPIO_SD_B1_11 (number 19), TakeUp Stepper MS2 */
#define BOARD_INITPINS_TAKEUP_STEPPER_MS2_GPIO                             GPIO3   /*!< GPIO device name: GPIO3 */
#define BOARD_INITPINS_TAKEUP_STEPPER_MS2_PORT                             GPIO3   /*!< PORT device name: GPIO3 */
#define BOARD_INITPINS_TAKEUP_STEPPER_MS2_PIN                                31U   /*!< GPIO3 pin index: 31 */

/* GPIO_SD_B1_10 (number 21), TakeUp Stepper MS1 */
#define BOARD_INITPINS_TAKEUP_STEPPER_MS1_GPIO                             GPIO3   /*!< GPIO device name: GPIO3 */
#define BOARD_INITPINS_TAKEUP_STEPPER_MS1_PORT                             GPIO3   /*!< PORT device name: GPIO3 */
#define BOARD_INITPINS_TAKEUP_STEPPER_MS1_PIN                                30U   /*!< GPIO3 pin index: 30 */


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
